export enum ErrorEnum {
  NOT_FOUND = '1001',
  INVALID_CREDENTIALS = '1002',
  UNAUTHORIZED_ACCESS = '1003',
  DUPLICATE_DATA = '1004',
  AUTHENTICATION_FAILED = '1006',
  DATA_FETCH_FAILED = '1007',
  UPDATE_FAILED = '1103',
  INVALID_AMOUNT = '1304',
  INSUFFICIENT_BALANCE = '1305',
  UPLOAD_FAILED = '1402',
  DOWNLOAD_FAILED = '1403',
  DELETE_FAILED = '1404',
  HEADERS_MISSING = '1501',
  SYSTEM_ERROR = '9999',
  DATABASE_ERROR = '9998',
  SERVICE_UNAVAILABLE = '9997',
  NOT_PROVIDED = '9996',
  DETACH_FAILED = '1405',
  INVALID_DATA = '1401',
  LOAD_FAILED = '1406',
  CORRUPTED_FILE = '1407',
  DATA_MISMATCH = '1408',
  DATA_EXISTS = '1409',
  INVALID_TOKEN = '1502',
  UNAUTHORIZED = '1503',
  INVALID_HMAC_SIGNATURE = '1504',
  INVALID_OR_EXPIRED_SESSION = '1505',
  INVALID_DEVICE_TOKEN = '1506',
  EXTERNAL_SERVICE_ERROR = '1507',
  VALIDATION_ERROR = '1508',
  INVALID_PERMISSION = '1509',
}
export const errorValues: Record<string, string> = {
  [ErrorEnum.NOT_FOUND]: 'not.found',
  [ErrorEnum.INVALID_CREDENTIALS]: 'invalid.credentials',
  [ErrorEnum.UNAUTHORIZED_ACCESS]: 'unauthorized.access',
  [ErrorEnum.DUPLICATE_DATA]: 'already.exists',
  [ErrorEnum.AUTHENTICATION_FAILED]: 'authentication.failed',
  [ErrorEnum.DATA_FETCH_FAILED]: 'data.fetch.failed',
  [ErrorEnum.UPDATE_FAILED]: 'update.failed',
  [ErrorEnum.INVALID_AMOUNT]: 'invalid.amount',
  [ErrorEnum.INSUFFICIENT_BALANCE]: 'insufficient.balance',
  [ErrorEnum.UPLOAD_FAILED]: 'upload.failed',
  [ErrorEnum.DOWNLOAD_FAILED]: 'download.failed',
  [ErrorEnum.DELETE_FAILED]: 'delete.failed',
  [ErrorEnum.HEADERS_MISSING]: 'headers.missing',
  [ErrorEnum.SYSTEM_ERROR]: 'system.error',
  [ErrorEnum.DATABASE_ERROR]: 'database.error',
  [ErrorEnum.SERVICE_UNAVAILABLE]: 'service.unavailable',
  [ErrorEnum.NOT_PROVIDED]: 'not.provided',
  [ErrorEnum.DETACH_FAILED]: 'detach.failed',
  [ErrorEnum.INVALID_DATA]: 'invalid.data',
  [ErrorEnum.LOAD_FAILED]: 'load.failed',
  [ErrorEnum.CORRUPTED_FILE]: 'corrupted.file',
  [ErrorEnum.DATA_MISMATCH]: 'data.mismatch',
  [ErrorEnum.DATA_EXISTS]: 'data.exists',
  [ErrorEnum.INVALID_TOKEN]: 'invalid.token',
  [ErrorEnum.UNAUTHORIZED]: 'unauthorized',
  [ErrorEnum.INVALID_HMAC_SIGNATURE]: 'invalid.hmac.signature',
  [ErrorEnum.INVALID_OR_EXPIRED_SESSION]: 'invalid.or.expired.session',
  [ErrorEnum.INVALID_DEVICE_TOKEN]: 'invalid.device.token',
  [ErrorEnum.EXTERNAL_SERVICE_ERROR]: 'external.service.error',
  [ErrorEnum.VALIDATION_ERROR]: 'validation.error',
  [ErrorEnum.INVALID_PERMISSION]: 'invalid.permission',
};
