export enum ExceptionType {
  DATA_NOT_FOUND = 'DATA_NOT_FOUND',
  INVALID_DATA = 'INVALID_DATA',
  DUPLICATE_DATA = 'DUPLICATE_DATA',
  MISSING_HEADER = 'MISSING_HEADER',
  UNAUTHORIZED = 'UNAUTHORIZED',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_PERMISSION = 'INVALID_PERMISSION',
  BAD_REQUEST = 'BAD_REQUEST',
}
